version: '3.4'

services:
  okx-master:
    image: okx-master
    build:
      context: .
      dockerfile: ./Dockerfile
      target: okx-master
    environment:
      NODE_ENV: production
    ports:
      - '8080:8080'
