// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

declare module '*.module.scss' {
  const classes: { readonly [key: string]: string };
  // eslint-disable-next-line import/no-default-export
  export default classes;
}

type ExposableObject<T extends object> = Omit<T, 'constructor'>;
type ExposablePropName<T extends object> = keyof ExposableObject<T>;

type ExposableType<T extends object> = {
  [P in keyof T]: T[P] extends (...args) => any ? T[P] : () => T[P];
};

type CryptoCurrency =
  | 'BTC'
  | 'ETH'
  | 'LTC'
  | 'XRP'
  | 'SOL'
  | 'BCH'
  | 'DOGE'
  | 'FIL'
  | 'ADA'
  | 'ETC';
type Quote = 'USDC' | 'USDT';

type InstId = `${CryptoCurrency}-${Quote}`;
